name: msgpack_serializable
description: A library for serializing and deserializing objects in the MessagePack format.
version: 0.0.0
repository: https://github.com/blimster/msgpack_serializable
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.2.0
  build: ^2.4.0
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  msgpack_annotation:
    path: ../annotation
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^5.0.0
  msgpack_dart: ^1.0.1
