name: msgpack_annotation
description: Annotations for msgpack serialization.
version: 0.1.0
repository: https://github.com/blimster/msgpack_serializable

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  msgpack_dart: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
